server:
  servlet:
    context-path: ${context:/codenjoy-balancer}

mvc:
  cache-period: 259200

log:
  debug: false

admin:
  login: admin@codenjoyme.com
  password: admin

score:
  update:
    time: 10000

sender:
    pool.size: 100

game:
  type: bomberman
  servers: localhost:8080
  schema: http
  basic-auth-user: admin@codenjoyme.com
  basic-auth-password: admin
  room: 10
  start-day: "2020-03-01"
  end-day: "2020-03-31"
  finalists-count: 10
  final-time: "19:00"

sms:
  enabled: false
  static-verification-code: 123456
  static-password: 12345678
  password-length: 8
  code-length: 6
  text:
    registration: "Your registration confirmation code: %s.\nCodenjoy Team."
    reset-password: "Your password confirmation code: %s.\nCodenjoy Team."
    new-password: "Your password has been changed. \nNew password: %s.\nCodenjoy Team."
  gateway:
    send-endpoint: http://sms-fly.com/api/api.noai.php
    user: 380989207390
    password: 123456789

messages:
  invalid-player-id: "Invalid playerId format: '%s'"
  invalid-player-email: "Invalid email format: '%s'"
  invalid-player-code: "Invalid code format: '%s'"
  invalid-game-name: "Invalid gameName format: '%s'"
  invalid-password: "Invalid password: '%s'"
  invalid-email-login-data: "Invalid email and/or password"
  invalid-code-login-data: "Invalid email and/or code"
  invalid-phone-login-data: "Invalid email and/or phone number"
  invalid-day: "Invalid date format (expected YYYY-MM-DD): '%s'"
  invalid-string: "Expected not empty %s string: '%s'"
  invalid-string-format: "Invalid characters used in %s (expected '%s') and/or exceeding the maximum length by %s characters: '%s'"
  should-be-empty: "An empty line is expected %s: '%s'"
  invalid-phone-number: "Invalid phone number format (expected +380XXYYYZZAA): '%s'"
  invalid-parameters: "There are errors: %s"
  already-registered-email: "The user with the specified email is already registered: '%s'"
  already-registered-phone: "A user with the specified phone number is already registered: '%s'"
  not-approved: "User not verified"
  already-approved: "The user has already been verified"
  not-found-email: "No user with email specified: '%s'"
  not-found-phone: "No user was found with the specified phone number: '%s'"
  invalid-verification-code: "Invalid confirmation code: '%s'"
  something-wrong: "Omg! Something went wrong. Save the ticket number and contact the organizer"