server:
  servlet:
    context-path: ${context:/codenjoy-balancer}

mvc:
  cache-period: 259200

log:
  debug: false

admin:
  login: admin@codenjoyme.com
  password: admin

email:
  hash: secureSoul

score:
  update:
    time: 10000

sender:
    pool.size: 100

game:
  type: bomberman
  servers: localhost:8080
  schema: http
  basic-auth-user: admin@codenjoyme.com
  basic-auth-password: admin
  room: 10
  start-day: "2020-03-01"
  end-day: "2020-03-31"
  finalists-count: 10
  final-time: "19:00"

sms:
  enabled: false
  static-verification-code: 123456
  static-password: 12345678
  text:
    registration: "Vash kod pidtverdzennya reestratsui: %s.\nCodenjoy Team."
    reset-password: "Vash kod pidtverdzennya zminy parolu: %s.\nCodenjoy Team."
    new-password: "Vash parol zmineno.\nNovyi parol: %s.\nCodenjoy Team."
  gateway:
    send-endpoint: http://sms-fly.com/api/api.noai.php
    user: 380989207390
    password: 123456789